### ISSUE TITLE
[bug] trait parse failures

### ISSUE THREAD

**Issue by evolbug** [wu-lang/wu#32]
Trait body fails to parse if there's an additional newline or comment

```rs
Data_T: trait {

    getFFIPointer:  fun(self) -> any
}
```

error:
```
wrong: expected `Identifier`, found `EOL`
thread 'main' panicked at 'byte index 1 is out of bounds of ``', /home/evol/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/str/mod.rs:1920:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     --> main.wu
```

```rs
Data_T: trait {
    getFFIPointer:  fun(self) -> any
    #asd

}
```
error:
```
wrong: expected `Identifier`, found `EOL`
thread 'main' panicked at 'byte index 9 is out of bounds of `    #asd`', /home/evol/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/str/mod.rs:1920:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
     --> main.wu
```

**Comment by nilq** [comment]
It's done.
